-- Session bearer and CSRF values are generated by the application. PostgreSQL
-- stores only their hashes; existing rows cannot be given a recoverable CSRF
-- value, so they are retained for audit and conservatively revoked below.
ALTER TABLE "sessions" RENAME COLUMN "expires_at" TO "idle_expires_at";
ALTER INDEX "sessions_user_id_expires_at_idx"
    RENAME TO "sessions_user_id_idle_expires_at_idx";
ALTER INDEX "sessions_expires_at_idx"
    RENAME TO "sessions_idle_expires_at_idx";

ALTER TABLE "sessions"
    ADD COLUMN "csrf_hash" VARCHAR(255),
    ADD COLUMN "absolute_expires_at" TIMESTAMPTZ(3),
    ADD COLUMN "last_activity_at" TIMESTAMPTZ(3),
    ADD COLUMN "last_rotated_at" TIMESTAMPTZ(3);

-- Infer the original absolute deadline from the first session in each existing
-- replacement chain. Historical data may contain a replacement created after
-- that inferred deadline because the old schema had no absolute lifetime. Every
-- legacy row is revoked below, so such a descendant receives only the minimum
-- representable finite deadline after its own creation. This satisfies the new
-- ordering constraints without extending usable legacy authentication. Rows
-- without predecessors are roots; UNION prevents duplicate work.
WITH RECURSIVE "session_chain" AS (
    SELECT
        root."id",
        root."rotated_to_id",
        root."created_at" AS "root_created_at"
    FROM "sessions" AS root
    WHERE NOT EXISTS (
        SELECT 1
        FROM "sessions" AS predecessor
        WHERE predecessor."rotated_to_id" = root."id"
    )

    UNION

    SELECT
        replacement."id",
        replacement."rotated_to_id",
        chain."root_created_at"
    FROM "session_chain" AS chain
    JOIN "sessions" AS replacement
      ON replacement."id" = chain."rotated_to_id"
)
UPDATE "sessions" AS session
SET "absolute_expires_at" = GREATEST(
    chain."root_created_at" + INTERVAL '90 days',
    session."created_at" + INTERVAL '1 millisecond'
)
FROM "session_chain" AS chain
WHERE session."id" = chain."id";

-- A malformed historical cycle has no root and therefore cannot be assigned a
-- trustworthy original deadline. Fail closed rather than silently extending it.
DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM "sessions"
        WHERE "absolute_expires_at" IS NULL
    ) THEN
        RAISE EXCEPTION 'cannot infer an absolute lifetime for a legacy session chain';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM "sessions" AS current_session
        JOIN "sessions" AS replacement
          ON replacement."id" = current_session."rotated_to_id"
        WHERE current_session."id" = replacement."id"
           OR current_session."user_id" <> replacement."user_id"
           OR replacement."created_at" < current_session."created_at"
    ) THEN
        RAISE EXCEPTION 'legacy session replacement chain is invalid';
    END IF;
END;
$$;

UPDATE "sessions"
SET
    "csrf_hash" = 'legacy-revoked:' || "id"::text,
    "last_activity_at" = "created_at",
    "last_rotated_at" = "created_at",
    "idle_expires_at" = LEAST(
        GREATEST("idle_expires_at", "created_at" + INTERVAL '1 millisecond'),
        "created_at" + INTERVAL '30 days',
        "absolute_expires_at"
    ),
    "revoked_at" = COALESCE(
        "revoked_at",
        GREATEST(CURRENT_TIMESTAMP, "created_at")
    );

ALTER TABLE "sessions"
    ALTER COLUMN "csrf_hash" SET NOT NULL,
    ALTER COLUMN "absolute_expires_at" SET NOT NULL,
    ALTER COLUMN "last_activity_at" SET NOT NULL,
    ALTER COLUMN "last_rotated_at" SET NOT NULL,
    ADD CONSTRAINT "sessions_csrf_hash_check" CHECK (
        length("csrf_hash") >= 32
    ),
    ADD CONSTRAINT "sessions_lifetime_order_check" CHECK (
        "last_activity_at" >= "created_at"
        AND "last_rotated_at" >= "created_at"
        AND "last_rotated_at" <= "last_activity_at"
        AND "idle_expires_at" > "last_activity_at"
        AND "idle_expires_at" <= "last_activity_at" + INTERVAL '30 days'
        AND "idle_expires_at" <= "absolute_expires_at"
        AND "absolute_expires_at" > "created_at"
        AND "absolute_expires_at" <= "created_at" + INTERVAL '90 days'
    ),
    ADD CONSTRAINT "sessions_revocation_state_check" CHECK (
        ("revoked_at" IS NULL OR "revoked_at" >= "created_at")
        AND ("rotated_to_id" IS NULL OR "revoked_at" IS NOT NULL)
        AND ("rotated_to_id" IS NULL OR "rotated_to_id" <> "id")
    );

-- Immutable security material and monotonic terminal/activity state prevent a
-- later update from reviving or silently re-keying an established session.
CREATE FUNCTION "enforce_session_security_update"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    IF NEW."user_id" IS DISTINCT FROM OLD."user_id"
       OR NEW."token_hash" IS DISTINCT FROM OLD."token_hash"
       OR NEW."csrf_hash" IS DISTINCT FROM OLD."csrf_hash"
       OR NEW."absolute_expires_at" IS DISTINCT FROM OLD."absolute_expires_at"
       OR NEW."last_rotated_at" IS DISTINCT FROM OLD."last_rotated_at"
       OR NEW."created_at" IS DISTINCT FROM OLD."created_at" THEN
        RAISE EXCEPTION 'session security identity and absolute lifetime are immutable';
    END IF;

    IF NEW."last_activity_at" < OLD."last_activity_at" THEN
        RAISE EXCEPTION 'session activity cannot move backwards';
    END IF;

    IF OLD."revoked_at" IS NOT NULL
       AND NEW."revoked_at" IS DISTINCT FROM OLD."revoked_at" THEN
        RAISE EXCEPTION 'session revocation is terminal';
    END IF;

    IF OLD."rotated_to_id" IS NOT NULL
       AND NEW."rotated_to_id" IS DISTINCT FROM OLD."rotated_to_id" THEN
        RAISE EXCEPTION 'session replacement is terminal';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER "sessions_security_update_trigger"
BEFORE UPDATE ON "sessions"
FOR EACH ROW
EXECUTE FUNCTION "enforce_session_security_update"();

-- A replacement must already exist, belong to the same user, and retain the
-- original absolute deadline before the old bearer can be marked rotated.
CREATE FUNCTION "enforce_session_rotation_chain"()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
DECLARE
    replacement "sessions"%ROWTYPE;
BEGIN
    IF NEW."rotated_to_id" IS NULL
       OR NEW."rotated_to_id" IS NOT DISTINCT FROM OLD."rotated_to_id" THEN
        RETURN NEW;
    END IF;

    SELECT *
    INTO replacement
    FROM "sessions"
    WHERE "id" = NEW."rotated_to_id";

    IF NOT FOUND
       OR replacement."user_id" <> NEW."user_id"
       OR replacement."absolute_expires_at" <> NEW."absolute_expires_at"
       OR replacement."created_at" < NEW."created_at"
       OR replacement."created_at" > NEW."revoked_at" THEN
        RAISE EXCEPTION 'invalid session replacement chain';
    END IF;

    RETURN NEW;
END;
$$;

CREATE TRIGGER "sessions_rotation_chain_trigger"
BEFORE UPDATE OF "rotated_to_id" ON "sessions"
FOR EACH ROW
EXECUTE FUNCTION "enforce_session_rotation_chain"();

CREATE INDEX "sessions_absolute_expires_at_idx"
    ON "sessions"("absolute_expires_at");

CREATE INDEX "sessions_user_active_expiry_idx"
    ON "sessions"("user_id", "revoked_at", "absolute_expires_at", "idle_expires_at");

-- Rate rows are immutable request attempts. The application HMACs the source
-- address before insertion; the shape constraint accepts canonical 256-bit
-- base64url or lowercase hexadecimal encodings and rejects ordinary IP text.
CREATE TYPE "AuthRateAction" AS ENUM (
    'magicLinkInitiation',
    'magicLinkRedemption'
);

CREATE TABLE "auth_rate_events" (
    "id" UUID NOT NULL,
    "action" "AuthRateAction" NOT NULL,
    "normalized_email" VARCHAR(320),
    "source_ip_digest" VARCHAR(64) NOT NULL,
    "occurred_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "auth_rate_events_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "auth_rate_events_email_scope_check" CHECK (
        (
            "action" = 'magicLinkInitiation'
            AND "normalized_email" IS NOT NULL
            AND "normalized_email" <> ''
            AND "normalized_email" = lower(btrim("normalized_email"))
        )
        OR (
            "action" = 'magicLinkRedemption'
            AND "normalized_email" IS NULL
        )
    ),
    CONSTRAINT "auth_rate_events_ip_digest_check" CHECK (
        "source_ip_digest" ~ '^[A-Za-z0-9_-]{43}$'
        OR "source_ip_digest" ~ '^[0-9a-f]{64}$'
    )
);

CREATE INDEX "auth_rate_events_email_window_idx"
    ON "auth_rate_events"("action", "normalized_email", "occurred_at");

CREATE INDEX "auth_rate_events_ip_window_idx"
    ON "auth_rate_events"("action", "source_ip_digest", "occurred_at");

CREATE INDEX "auth_rate_events_occurred_at_idx"
    ON "auth_rate_events"("occurred_at");

CREATE TYPE "AuthSecurityEventKind" AS ENUM (
    'magicLinkIssueSucceeded',
    'magicLinkIssueFailed',
    'magicLinkRedemptionSucceeded',
    'magicLinkRedemptionFailed',
    'magicLinkRevoked',
    'sessionCreated',
    'sessionRotated',
    'sessionRevoked',
    'userSessionsRevoked'
);

CREATE TABLE "auth_security_events" (
    "id" UUID NOT NULL,
    "kind" "AuthSecurityEventKind" NOT NULL,
    "user_id" UUID,
    "session_id" UUID,
    "source_ip_digest" VARCHAR(64),
    "occurred_at" TIMESTAMPTZ(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "auth_security_events_pkey" PRIMARY KEY ("id"),
    CONSTRAINT "auth_security_events_ip_digest_check" CHECK (
        "source_ip_digest" IS NULL
        OR "source_ip_digest" ~ '^[A-Za-z0-9_-]{43}$'
        OR "source_ip_digest" ~ '^[0-9a-f]{64}$'
    )
);

CREATE INDEX "auth_security_events_kind_order_idx"
    ON "auth_security_events"("kind", "occurred_at", "id");

CREATE INDEX "auth_security_events_user_order_idx"
    ON "auth_security_events"("user_id", "occurred_at", "id");

CREATE INDEX "auth_security_events_session_order_idx"
    ON "auth_security_events"("session_id", "occurred_at", "id");

ALTER TABLE "auth_security_events"
    ADD CONSTRAINT "auth_security_events_user_id_fkey"
    FOREIGN KEY ("user_id") REFERENCES "users"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE,
    ADD CONSTRAINT "auth_security_events_session_id_fkey"
    FOREIGN KEY ("session_id") REFERENCES "sessions"("id")
    ON DELETE RESTRICT ON UPDATE CASCADE;
